name: xhs_app
description: "xiaohongshu application"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.3.1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  crypto: ^3.0.3
  device_info_plus: ^10.1.2
  dio: ^5.5.0+1
  encrypt: ^5.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.4
  shelf_proxy: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.0
  get: ^4.6.6
  flutter_udid: ^3.0.0
  package_info_plus: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  infinite_scroll_pagination: ^4.1.0
  lazy_load_indexed_stack: ^1.1.0
  carousel_slider: ^5.0.0
  webviewx_plus: ^0.5.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.14.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  marqueer: ^2.0.1
  video_player: ^2.9.1
  easy_refresh: ^3.4.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.2
  buttons_tabbar: ^1.3.13
  flutter_staggered_grid_view: ^0.7.0
  easy_rich_text: ^2.1.0
  tuple: ^2.0.2
  qr_flutter: ^4.0.0
  slide_countdown: ^1.6.1
  json2dart_safe: ^1.5.8
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  date_format: ^2.0.9
  flutter_smart_dialog: ^4.9.8
  # Riverpod核心库
  flutter_riverpod: ^2.5.1
  # Riverpod注解生成器
  riverpod_annotation: ^2.3.5
  #  common_utils: ^2.1.0 # 没有用到先注释，运行一段时间发现没问题再删除
  collection: ^1.18.0 # 有间接依赖到
  video_player_web_hls: ^1.3.0
  video_player_web: ^2.3.2
  file_picker: ^9.0.0
  photo_view: ^0.15.0
  #  path: ^1.9.0 # 没有用到先注释，运行一段时间发现没问题再删除
  scan: ^1.6.0
  circular_buffer: ^0.12.0
  scrollview_observer: ^1.22.0
  background_app_bar: ^2.1.0
  city_pickers: ^1.3.0 # 城市选择器
  restart_app: ^1.2.1
  flutter_cupertino_date_picker_fork: ^1.0.7
  hive_generator: ^2.0.1
  downloadsfolder: ^1.1.0
  loading_animation_widget: ^1.3.0
  dia_static: ^0.1.2
  device_uuid: ^0.0.4
  wakelock_plus: ^1.2.8
  connectivity_plus: ^6.1.0 #网络状态检测
  extended_nested_scroll_view: ^6.2.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  event_bus: ^2.0.1
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  flutter_slidable: ^3.1.2
  animated_reorderable_list: ^1.2.0
  expandable_richtext: ^1.0.7
  blur: ^4.0.0
  badges: ^3.1.2
  install_plugin: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_inappwebview: ^6.1.5
dev_dependencies:
  # 生成器
  build_runner: ^2.4.9
  # 序列化
  json_serializable: ^6.8.0
  # 数据模型
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  meta: ^1.14.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/
    - assets/images/mine/
    - assets/images/mine/vip_badge/
    - assets/images/search/
    - assets/images/player/
    - assets/images/ann/
    - assets/images/short/
    - assets/images/community/
    - assets/images/community/discover/
    - assets/images/community/attention/
    - assets/images/community/complaint/
    - assets/images/community/detail/
    - assets/images/icon/
    - assets/images/shi_pin/
    - assets/images/home/
    - assets/images/home/check_in/
    - assets/images/icon/
    - assets/images/selection/
    - assets/json/

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
